class LeveeException(Exception):
    """Any exception generated by this package"""
    pass

class ChartSyntaxError(LeveeException):
    """A chart exception caught during class creation"""
    pass

class TransitionError(LeveeException):
    """An error thrown when the transition fails"""
    pass

class TransitionDoesNotExist(TransitionError): pass
class TransitionMissingArgs(TransitionError): pass
class TransitionNotAllowed(TransitionError): pass